# permissions to do viewer deployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployment-viewer-role
rules:
- apiGroups:
  - ml.tribit.io
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ml.tribit.io
  resources:
  - deployments/status
  verbs:
  - get
