
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ml.tribit.io
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ml.tribit.io
  resources:
  - deployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ml.tribit.io
  resources:
  - trainings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ml.tribit.io
  resources:
  - trainings/status
  verbs:
  - get
  - patch
  - update
