# permissions to do viewer trainings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: training-viewer-role
rules:
- apiGroups:
  - ml.tribit.io
  resources:
  - trainings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ml.tribit.io
  resources:
  - trainings/status
  verbs:
  - get
